# Generated by Django 3.2.9 on 2022-03-03 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(choices=[('Cinema city', 'Cinema city'), ('Helios', 'Helios'), ('Multikino', 'Multikino'), ('Other', 'Other')], default='Cinema city', max_length=255)),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('clicked', models.IntegerField()),
                ('version', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2)),
                ('language', models.CharField(choices=[('ENG', 'ENG (NAPISY PL)'), ('PL', 'PL'), ('DUB', 'DUBBING PL')], default='ENG', max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PerformanceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cinema.date')),
                ('schedule', models.ManyToManyField(to='cinema.PerformanceTime')),
            ],
        ),
        migrations.CreateModel(
            name='MovieBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cinema.building', to_field='name')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='cinema.movie')),
            ],
            options={
                'ordering': ('building',),
            },
        ),
        migrations.AddField(
            model_name='date',
            name='movie_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='cinema.moviebuilding'),
        ),
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.category', to_field='name'),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='cinema.city', to_field='name'),
        ),
    ]
