# Generated by Django 3.2.9 on 2021-12-08 12:04

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Cinema city', 'Cinema city'), ('Helios', 'Helios'), ('Multikino', 'Multikino'), ('Other', 'Other')], default='Cinema city', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2)),
                ('genre', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('ENG', 'ENG (NAPISY PL)'), ('PL', 'PL'), ('DUB', 'DUBBING PL')], default='ENG', max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('slug', models.SlugField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.building', to_field='name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.category', to_field='name'),
        ),
    ]
