version: '3.3'

volumes:
  filmarket_prod_data: {}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: production_backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start_prod
    restart: always
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    container_name: production_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend/nginx:/etc/nginx/conf.d
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:15.1
    container_name: production_db
    volumes:
      - filmarket_prod_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432